services:
  app:
    container_name: shortener
    hostname: shortener
    build:
        context: .
        dockerfile: ./build/shortener.Dockerfile
    env_file:
      - example.env
    ports:
      - "8080:8080"
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    container_name: postgres
    hostname: postgres
    image: "postgres:16.3-alpine"
    env_file:
      - example.env
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"