// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: test.sql

package repo

import (
	"context"
)

const selectNow = `-- name: SelectNow :one
SELECT NOW() as now
`

func (q *Queries) SelectNow(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, selectNow)
	var now interface{}
	err := row.Scan(&now)
	return now, err
}
